English version Readme
terminologieserver/postman_voorbeelden pull request #1
Opened 2021-05-28 06:51 UTC by micverb

2021-05-28 07:39 UTC, mertenssander requested changes

2021-05-28 07:39 UTC, mertenssander commented on README.md
> +*For  English click [here: ](https://github.com/micverb/postman_voorbeelden/blob/main/README_ENG.md)*
Zou je in plaats van deze regel het volgende bovenaan de readme kunnen zetten? Zo is de link relatief en valt hij meer op. Verder helemaal perfect!

# postman
## English version
*For  English click [__here__](README_ENG.md)*

## Introductie
Voorbeelden voor het gebruik van de FHIR API, gedocumenteerd als een Postman collectie. Importeer het JSON bestand in deze map in postman, en creëer een *environment* met variabelen *username* en *password*.

2021-05-28 11:30 UTC, micverb reviewed
Is aangepast. Volgens mij moet jij het wel alsnog approven.

2021-05-31 14:14 UTC, mertenssander approved these changes

2021-05-31 14:14 UTC, merged